import * as fs from 'node:fs';
import * as path from 'node:path';
import { parse as parseYaml } from 'yaml';
import { sortStages } from './topo-sort.js';
import type { PipelineStage } from './parser.js';

export interface WorkflowInitCandidate {
  id: string;
  workflowPath: string;
  triggers: string[];
}

export interface WorkflowInitResult {
  candidates: WorkflowInitCandidate[];
  stages: PipelineStage[];
  skipped: string[];
}

const LOCAL_WORKFLOW_REF =
  /(?:uses:\s*|\.\/)?\.github\/workflows\/([A-Za-z0-9_.-]+)\.(ya?ml)/gi;

function workflowStem(fileName: string): string {
  return fileName.replace(/\.(ya?ml)$/i, '');
}

function normalizeWorkflowPath(repoRoot: string, relativePath: string): string {
  return path.normalize(path.join(repoRoot, relativePath)).replace(/\\/g, '/');
}

function hasDispatchTrigger(onBlock: unknown): boolean {
  if (onBlock == null) {
    return false;
  }
  if (typeof onBlock === 'string') {
    return onBlock === 'workflow_dispatch' || onBlock === 'workflow_call';
  }
  if (Array.isArray(onBlock)) {
    return onBlock.some(
      (entry) => entry === 'workflow_dispatch' || entry === 'workflow_call',
    );
  }
  if (typeof onBlock === 'object') {
    const keys = Object.keys(onBlock as Record<string, unknown>);
    return keys.includes('workflow_dispatch') || keys.includes('workflow_call');
  }
  return false;
}

function collectTriggers(onBlock: unknown): string[] {
  if (onBlock == null) {
    return [];
  }
  if (typeof onBlock === 'string') {
    return [onBlock];
  }
  if (Array.isArray(onBlock)) {
    return onBlock.map(String);
  }
  if (typeof onBlock === 'object') {
    return Object.keys(onBlock as Record<string, unknown>);
  }
  return [];
}

function findReferencedWorkflowStems(content: string): Set<string> {
  const stems = new Set<string>();
  for (const match of content.matchAll(LOCAL_WORKFLOW_REF)) {
    stems.add(match[1]);
  }
  return stems;
}

export function scanWorkflowsForInit(repoRoot: string): WorkflowInitResult {
  const workflowsDir = path.join(repoRoot, '.github', 'workflows');
  if (!fs.existsSync(workflowsDir)) {
    return { candidates: [], stages: [], skipped: [] };
  }

  const entries = fs
    .readdirSync(workflowsDir)
    .filter((name) => name.endsWith('.yml') || name.endsWith('.yaml'))
    .sort();

  const candidates: WorkflowInitCandidate[] = [];
  const skipped: string[] = [];
  const pathByStem = new Map<string, string>();
  const contentByStem = new Map<string, string>();

  for (const entry of entries) {
    const stem = workflowStem(entry);
    const relativePath = path.join('.github', 'workflows', entry).replace(/\\/g, '/');
    const absolutePath = path.join(workflowsDir, entry);
    const content = fs.readFileSync(absolutePath, 'utf8');
    let doc: unknown;

    try {
      doc = parseYaml(content);
    } catch {
      skipped.push(`${relativePath} (invalid YAML)`);
      continue;
    }

    const onBlock = (doc as { on?: unknown })?.on;
    if (!hasDispatchTrigger(onBlock)) {
      skipped.push(`${relativePath} (no workflow_dispatch/workflow_call)`);
      continue;
    }

    pathByStem.set(stem, relativePath);
    contentByStem.set(stem, content);
    candidates.push({
      id: stem,
      workflowPath: relativePath,
      triggers: collectTriggers(onBlock),
    });
  }

  const needsByStem = new Map<string, Set<string>>();
  for (const candidate of candidates) {
    const stem = workflowStem(path.basename(candidate.workflowPath));
    const refs = findReferencedWorkflowStems(contentByStem.get(stem) ?? '');
    const needs = new Set<string>();
    for (const refStem of refs) {
      if (refStem === stem) {
        continue;
      }
      if (pathByStem.has(refStem)) {
        needs.add(refStem);
      }
    }
    needsByStem.set(stem, needs);
  }

  const stages: PipelineStage[] = candidates.map((candidate) => {
    const stem = workflowStem(path.basename(candidate.workflowPath));
    const needs = [...(needsByStem.get(stem) ?? [])].sort();
    return {
      id: candidate.id,
      workflow: candidate.workflowPath,
      ...(needs.length > 0 ? { needs } : {}),
    };
  });

  return {
    candidates,
    stages: sortStages(stages),
    skipped,
  };
}

export function renderInitPipelineYaml(stages: PipelineStage[], pipelineName = 'pipeline'): string {
  const lines: string[] = [
    `# Generated by pipeline-compose init — review needs, outputs, and inputs before use`,
    `name: ${pipelineName}`,
    'version: 1',
    'stages:',
  ];

  for (const stage of stages) {
    lines.push(`  - id: ${stage.id}`);
    lines.push(`    workflow: ${stage.workflow}`);
    if (stage.needs && stage.needs.length > 0) {
      lines.push('    needs:');
      for (const dep of stage.needs) {
        lines.push(`      - ${dep}`);
      }
    }
  }

  lines.push('');
  return lines.join('\n');
}

export function writeInitPipeline(
  repoRoot: string,
  options: { outputPath?: string; pipelineName?: string; force?: boolean } = {},
): { outputPath: string; result: WorkflowInitResult } {
  const result = scanWorkflowsForInit(repoRoot);
  if (result.stages.length === 0) {
    throw new Error(
      'No workflow_dispatch or workflow_call workflows found under .github/workflows/',
    );
  }

  const outputPath = path.resolve(
    repoRoot,
    options.outputPath ?? path.join('.github', 'pipelines', 'pipeline.yml'),
  );

  if (fs.existsSync(outputPath) && !options.force) {
    throw new Error(`Refusing to overwrite existing file: ${outputPath} (use --force)`);
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(
    outputPath,
    renderInitPipelineYaml(result.stages, options.pipelineName),
    'utf8',
  );

  return { outputPath, result };
}
