version: 2
companion_workflows:
  - .github/workflows/compile-check.yml
  - .github/workflows/pipeline-generated.yml
pipelines:
  pipeline:
    stages:
      - id: ci
        workflow: .github/workflows/ci.yml
      - id: deploy
        workflow: .github/workflows/deploy.yml
        needs:
          - ci
        when: startsWith(github.ref, 'refs/tags/v')
