name: pipeline
version: 1
stages:
  - id: ci
    workflow: .github/workflows/ci.yml
  - id: version-sync
    workflow: .github/workflows/stage-version-sync.yml
    needs:
      - ci
    outputs:
      - version
      - skip_publish
  - id: release-publish
    workflow: .github/workflows/stage-release-publish.yml
    needs:
      - version-sync
    inputs:
      version: ${{ context.version-sync.version }}
      skip_publish: ${{ context.version-sync.skip_publish }}
  - id: publish-actions
    workflow: .github/workflows/publish-actions.yml
    needs:
      - release-publish
    inputs:
      version: ${{ context.version-sync.version }}
