import { stringify as stringifyYaml } from 'yaml';
import type { Pipeline, PipelineStage } from './parser.js';

function normalizeWorkflowPath(workflow: string): string {
  if (workflow.startsWith('./')) {
    return workflow;
  }
  return `./${workflow}`;
}

function resolveInput(value: string): string {
  return value.replace(
    /\$\{\{\s*context\.([a-z0-9-]+)\.([a-z0-9_]+)\s*\}\}/gi,
    (_, stageId, output) => `\${{ needs.${stageId}.outputs.${output} }}`,
  );
}

function stageJob(stage: PipelineStage): Record<string, unknown> {
  const job: Record<string, unknown> = {
    uses: normalizeWorkflowPath(stage.workflow),
    secrets: 'inherit',
  };

  if (stage.needs?.length) {
    job.needs = stage.needs;
  }
  if (stage.when) {
    job.if = stage.when;
  }
  if (stage.environment) {
    job.environment = stage.environment;
  }
  if (stage.inputs && Object.keys(stage.inputs).length > 0) {
    job.with = Object.fromEntries(
      Object.entries(stage.inputs).map(([k, v]) => [k, resolveInput(v)]),
    );
  }

  return job;
}

export function generateWorkflow(pipeline: Pipeline): string {
  const jobs: Record<string, unknown> = {};
  for (const stage of pipeline.stages) {
    jobs[stage.id] = stageJob(stage);
  }

  const doc = {
    name: `Pipeline: ${pipeline.name}`,
    on: {
      workflow_call: {},
    },
    jobs,
  };

  const header = [
    '# Generated by pipeline-compose — do not edit manually',
    `# Source: .github/pipelines/${pipeline.name}.yml`,
    '',
  ].join('\n');

  return `${header}${stringifyYaml(doc)}`;
}
