name: Release
on:
  push:
    tags:
      - v*

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aeswibon/pipeline-compose-run@v1.9.0
        with:
          pipeline_file: .github/pipelines/pipeline.yml
