name: Tag release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  actions: write

concurrency:
  group: tag-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-tag-release-pipeline:
    name: Run tag-release pipeline
    uses: ./.github/workflows/tag-release.generated.yml
    secrets: inherit
